export function collectRefs(doc) {
  return {
    clientStage: doc.getElementById("client-stage"),
    clientScale: doc.getElementById("client-scale"),
    clientShell: doc.getElementById("client-shell"),
    viewport: doc.getElementById("viewport"),
    worldCanvas: doc.getElementById("world-canvas"),
    hintLabel: doc.getElementById("hint-label"),
    actorPlayer: doc.getElementById("actor-player"),
    actorTarget: doc.getElementById("actor-target"),
    topTabs: doc.getElementById("top-tabs"),
    bottomTabs: doc.getElementById("bottom-tabs"),
    panelTitle: doc.getElementById("panel-title"),
    panelSubtitle: doc.getElementById("panel-subtitle"),
    panelContent: doc.getElementById("panel-content"),
    chatLog: doc.getElementById("chat-log"),
    chatFilters: doc.getElementById("chat-filters"),
    chatChannelLabel: doc.getElementById("chat-channel-label"),
    chatInput: doc.getElementById("chat-input"),
    minimap: doc.getElementById("minimap"),
    minimapCanvas: doc.getElementById("minimap-canvas"),
    headingReadout: doc.getElementById("heading-readout"),
    mapPlayerDot: doc.getElementById("map-player-dot"),
    mapTargetDot: doc.getElementById("map-target-dot"),
    orbHp: doc.getElementById("orb-hp"),
    orbPrayer: doc.getElementById("orb-prayer"),
    orbRun: doc.getElementById("orb-run"),
    orbSpec: doc.getElementById("orb-spec"),
    orbHpValue: doc.getElementById("orb-hp-value"),
    orbPrayerValue: doc.getElementById("orb-prayer-value"),
    orbRunValue: doc.getElementById("orb-run-value"),
    orbSpecValue: doc.getElementById("orb-spec-value"),
    contextMenu: doc.getElementById("context-menu"),
    toastRack: doc.getElementById("toast-rack"),
  };
}
