import {
  LAYOUT_FIXED_CLASSIC,
  SCALING_LINEAR,
} from "./constants.js";

export function buildInventory() {
  return [
    { name: "Abyssal Whip", qty: 1 },
    { name: "Rune Platelegs", qty: 1 },
    { name: "Shark", qty: 7 },
    { name: "Lobster", qty: 3 },
    { name: "Prayer Potion(4)", qty: 4 },
    { name: "Law Rune", qty: 86 },
    { name: "Air Rune", qty: 352 },
    { name: "Coins", qty: 127054 },
    { name: "Teleport Tablet", qty: 6 },
    { name: "Stamina Potion", qty: 2 },
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
  ];
}

export function createInitialState() {
  return {
    runtime: {
      world: 302,
      startedAt: Date.now(),
      heading: 0,
    },
    ui: {
      activeGroup: "top",
      activeTop: "inventory",
      activeBottom: "friends",
      selectedItemIndex: null,
      selectedPrayer: "Thick Skin",
      selectedSpell: "Wind Strike",
      chatChannel: "All",
      contextOpen: false,
      contextPayload: null,
    },
    markers: {
      player: { x: 46, y: 55 },
      target: { x: 64, y: 44 },
    },
    stats: {
      hp: 92,
      maxHp: 99,
      prayer: 78,
      maxPrayer: 99,
      run: 84,
      spec: 100,
      quickPrayer: false,
      running: true,
      autoRetaliate: true,
      combatStyle: "Accurate",
      targetName: "Goblin Scout",
    },
    sailing: {
      route: "Port Sarim to Catherby",
      hull: 91,
      risk: 24,
      windAssist: true,
      preset: "Balanced",
    },
    progression: {
      combatLevel: 92,
      totalLevel: 1684,
      questPoints: 276,
      diaryProgress: 68,
      activePath: "Kandarin Route",
    },
    quests: {
      total: 158,
      completed: 114,
      inProgress: 7,
      highlighted: [
        "Desert Treasure II",
        "Sins of the Father",
        "Song of the Elves",
      ],
    },
    inventory: buildInventory(),
    equipment: {
      head: "Rune Full Helm",
      cape: "Ardougne Cloak",
      neck: "Amulet of Glory",
      weapon: "Abyssal Whip",
      body: "Fighter Torso",
      shield: "Dragon Defender",
      legs: "Rune Platelegs",
      gloves: "Barrows Gloves",
      boots: "Dragon Boots",
      ring: "Berserker Ring",
      ammo: "Diamond Bolts",
    },
    prices: {
      "Abyssal Whip": 2298000,
      "Rune Platelegs": 38600,
      Shark: 857,
      Lobster: 178,
      "Prayer Potion(4)": 8290,
      "Law Rune": 141,
      "Air Rune": 4,
      Coins: 1,
      "Teleport Tablet": 362,
      "Stamina Potion": 8745,
    },
    prayers: [
      "Thick Skin",
      "Burst of Strength",
      "Clarity of Thought",
      "Protect from Magic",
      "Protect from Missiles",
      "Protect from Melee",
      "Piety",
      "Rigour",
      "Augury",
    ],
    spells: [
      "Wind Strike",
      "Water Strike",
      "Fire Bolt",
      "Crumble Undead",
      "Varrock Teleport",
      "Falador Teleport",
      "High Alchemy",
      "Snare",
    ],
    social: {
      friends: [
        { name: "Stone Lynx", world: 302, online: true },
        { name: "Mist Falcon", world: 325, online: true },
        { name: "Mire Finch", world: 0, online: false },
      ],
      ignores: ["bot_runner_03", "goldspam_q7"],
      clan: "Dawn Watch",
      channel: "Lakeside Ops",
      groupingRole: "Scout",
      groupingCooldown: 96,
    },
    settings: {
      gameClientLayout: LAYOUT_FIXED_CLASSIC,
      interfaceScale: 1,
      interfaceScalingMode: SCALING_LINEAR,
      brightness: 62,
      musicVolume: 54,
      effectVolume: 66,
      showGroundItems: true,
      profanityFilter: true,
      roofHiding: true,
      chatTimestamps: false,
    },
    music: {
      nowPlaying: "Sea Shanty 2",
      mode: "Shuffle",
      unlocked: 141,
    },
    chat: {
      entries: [
        { channel: "System", text: "Client initialized." },
        { channel: "Game", text: "You feel rested and ready to adventure." },
        { channel: "Clan", text: "Meet at Catherby docks in 5 minutes." },
      ],
    },
  };
}
